/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Coinone REST Public API
 * 코인원 공식 문서 v1.7 기준 Public REST API 스펙입니다.
 * OpenAPI spec version: 1.7
 */
import * as zod from 'zod';

/**
 * 개별 종목의 가격 단위 별 호가 단위 조회
 * @summary 개별 호가 단위 조회
 */
export const rangeUnitPathQuoteCurrencyDefault = `KRW`;
export const rangeUnitPathTargetCurrencyDefault = `BTC`;

export const RangeUnitParams = zod.object({
  "quote_currency": zod.string().default(rangeUnitPathQuoteCurrencyDefault).describe('마켓 기준 통화 (예: KRW)'),
  "target_currency": zod.string().default(rangeUnitPathTargetCurrencyDefault).describe('조회하려는 종목의 심볼 (예: BTC)')
})


/**
 * 마켓 별로 거래 가능한 종목들의 정보 조회
 * @summary 전체 종목 정보 조회
 */
export const marketsPathQuoteCurrencyDefault = `KRW`;

export const MarketsParams = zod.object({
  "quote_currency": zod.string().default(marketsPathQuoteCurrencyDefault).describe('마켓 기준 통화')
})


/**
 * 마켓 별로 거래 가능한 개별 종목의 정보 조회
 * @summary 개별 종목 정보 조회
 */
export const marketPathQuoteCurrencyDefault = `KRW`;
export const marketPathTargetCurrencyDefault = `BTC`;

export const MarketParams = zod.object({
  "quote_currency": zod.string().default(marketPathQuoteCurrencyDefault).describe('마켓 기준 통화'),
  "target_currency": zod.string().default(marketPathTargetCurrencyDefault).describe('조회하려는 종목의 심볼')
})


/**
 * 특정 종목의 오더북 정보 조회 (호가 단위 별)
 * @summary 오더북 조회
 */
export const orderbookPathQuoteCurrencyDefault = `KRW`;
export const orderbookPathTargetCurrencyDefault = `BTC`;

export const OrderbookParams = zod.object({
  "quote_currency": zod.string().default(orderbookPathQuoteCurrencyDefault).describe('마켓 기준 통화'),
  "target_currency": zod.string().default(orderbookPathTargetCurrencyDefault).describe('조회하려는 종목의 심볼')
})

export const orderbookQuerySizeDefault = `15`;

export const OrderbookQueryParams = zod.object({
  "size": zod.enum(['5', '10', '15', '16']).default(orderbookQuerySizeDefault).describe('조회 하려는 오더북 개수 (기본값: 15)'),
  "order_book_unit": zod.number().optional().describe('Market API의 order_book_units 값 사용. 아닐경우, 표준 오더북 반환')
})


/**
 * 최신 순으로 체결된 주문 목록 조회
 * @summary 최근 체결 주문 조회
 */
export const recentCompletedOrdersPathQuoteCurrencyDefault = `KRW`;
export const recentCompletedOrdersPathTargetCurrencyDefault = `BTC`;

export const RecentCompletedOrdersParams = zod.object({
  "quote_currency": zod.string().default(recentCompletedOrdersPathQuoteCurrencyDefault).describe('마켓 기준 통화'),
  "target_currency": zod.string().default(recentCompletedOrdersPathTargetCurrencyDefault).describe('조회하려는 종목의 심볼')
})

export const recentCompletedOrdersQuerySizeDefault = `200`;

export const RecentCompletedOrdersQueryParams = zod.object({
  "size": zod.enum(['10', '50', '100', '150', '200']).default(recentCompletedOrdersQuerySizeDefault).describe('한번에 조회할 목록 수 (기본:200)')
})


/**
 * 마켓의 모든 티커 정보 조회
 * @summary 전체 티커 정보 조회
 */
export const tickersPathQuoteCurrencyDefault = `KRW`;

export const TickersParams = zod.object({
  "quote_currency": zod.string().default(tickersPathQuoteCurrencyDefault).describe('조회하려는 마켓의 기준 통화')
})

export const tickersQueryAdditionalDataDefault = false;

export const TickersQueryParams = zod.object({
  "additional_data": zod.boolean().default(tickersQueryAdditionalDataDefault).describe('입력 값이 true 이면 전일가 정보까지 조회')
})


/**
 * 특정 종목의 티커 정보 조회
 * @summary 개별 티커 정보 조회
 */
export const tickerPathQuoteCurrencyDefault = `KRW`;
export const tickerPathTargetCurrencyDefault = `BTC`;

export const TickerParams = zod.object({
  "quote_currency": zod.string().default(tickerPathQuoteCurrencyDefault).describe('마켓의 기준 통화'),
  "target_currency": zod.string().default(tickerPathTargetCurrencyDefault).describe('조회하려는 종목의 심볼')
})

export const tickerQueryAdditionalDataDefault = false;

export const TickerQueryParams = zod.object({
  "additional_data": zod.boolean().default(tickerQueryAdditionalDataDefault).describe('입력 값이 true 이면 전일가 정보까지 조회')
})


/**
 * UTC 기준으로 마켓의 모든 티커 정보 조회
 * @summary 전체 티커 정보 조회 (UTC)
 */
export const utcTickersPathQuoteCurrencyDefault = `KRW`;

export const UtcTickersParams = zod.object({
  "quote_currency": zod.string().default(utcTickersPathQuoteCurrencyDefault).describe('조회하려는 마켓의 기준 통화')
})

export const utcTickersQueryAdditionalDataDefault = true;

export const UtcTickersQueryParams = zod.object({
  "additional_data": zod.boolean().default(utcTickersQueryAdditionalDataDefault).describe('입력 값이 true 이면 전일가 정보까지 조회')
})


/**
 * UTC 기준으로 특정 종목의 티커 정보 조회
 * @summary 개별 티커 정보 조회 (UTC)
 */
export const utcTickerPathQuoteCurrencyDefault = `KRW`;
export const utcTickerPathTargetCurrencyDefault = `BTC`;

export const UtcTickerParams = zod.object({
  "quote_currency": zod.string().default(utcTickerPathQuoteCurrencyDefault).describe('마켓의 기준 통화'),
  "target_currency": zod.string().default(utcTickerPathTargetCurrencyDefault).describe('조회하려는 종목의 심볼')
})

export const utcTickerQueryAdditionalDataDefault = true;

export const UtcTickerQueryParams = zod.object({
  "additional_data": zod.boolean().default(utcTickerQueryAdditionalDataDefault).describe('입력 값이 true 이면 전일가 정보까지 조회')
})


/**
 * 특정 종목의 정보 조회 (심볼 정보, 입/출금 가능여부, 입/출금 수수료, 최소 출금 가능 금액 등)
 * @summary 개별 가상자산 정보 조회
 */
export const currencyPathCurrencyDefault = `BTC`;

export const CurrencyParams = zod.object({
  "currency": zod.string().default(currencyPathCurrencyDefault).describe('조회하려는 종목의 심볼')
})


/**
 * 특정 종목의 캔들 차트 조회
 * @summary 캔들 차트 조회
 */
export const chartPathQuoteCurrencyDefault = `KRW`;
export const chartPathTargetCurrencyDefault = `BTC`;

export const ChartParams = zod.object({
  "quote_currency": zod.string().default(chartPathQuoteCurrencyDefault).describe('마켓 기준 통화'),
  "target_currency": zod.string().default(chartPathTargetCurrencyDefault).describe('조회하려는 종목의 심볼')
})

export const chartQuerySizeDefault = 200;

export const ChartQueryParams = zod.object({
  "interval": zod.enum(['1m', '3m', '5m', '15m', '30m', '1h', '2h', '4h', '6h', '1d', '1w', '1mon']).describe('차트 간격'),
  "timestamp": zod.string().optional().describe('마지막 캔들의 타임스탬프 (UTC 기준 시간 입력, Unix time, ms)'),
  "size": zod.number().default(chartQuerySizeDefault).describe('조회할 캔들 수 (최소 1~최대 500) 미입력시 default: 200')
})


/**
 * 특정 종목의 오더북 정보 조회
 * @deprecated
 * @summary 오더북 조회
 */
export const orderbookDeprecatedQueryCurrencyDefault = `BTC`;

export const OrderbookDeprecatedQueryParams = zod.object({
  "currency": zod.string().default(orderbookDeprecatedQueryCurrencyDefault).describe('조회하려는 종목의 심볼')
})


/**
 * 마켓의 모든 티커 정보 조회
 * @deprecated
 * @summary 티커 정보 조회
 */
export const ticker1QueryCurrencyDefault = `BTC`;

export const Ticker1QueryParams = zod.object({
  "currency": zod.string().default(ticker1QueryCurrencyDefault).describe('조회하려는 종목의 심볼. 유효하지 않은 심볼 입력 시 전체 티커 정보가 조회 됨')
})


/**
 * UTC 기준으로 마켓의 모든 티커 정보 조회
 * @deprecated
 * @summary 티커 정보 조회 UTC
 */
export const tickerUtcDeprecatedQueryCurrencyDefault = `BTC`;

export const TickerUtcDeprecatedQueryParams = zod.object({
  "currency": zod.string().default(tickerUtcDeprecatedQueryCurrencyDefault).describe('조회하려는 종목의 심볼. 유효하지 않은 심볼 입력 시 전체 티커 정보가 조회 됨')
})


/**
 * 최신 순으로 체결된 주문 목록 조회
 * @deprecated
 * @summary 최근 체결 주문 조회
 */
export const recentCompleteOrdersDeprecatedQueryCurrencyDefault = `BTC`;

export const RecentCompleteOrdersDeprecatedQueryParams = zod.object({
  "currency": zod.string().default(recentCompleteOrdersDeprecatedQueryCurrencyDefault).describe('조회하려는 종목의 심볼')
})
