/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * GOPAX Private REST API
 * 고팍스 공식 문서 기준 스펙입니다.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary 잔고 조회
 */
export const getbalancesHeaderReceiveWindowMin = 200;
export const getbalancesHeaderReceiveWindowMax = 60000;



export const GetbalancesHeader = zod.object({
  "timestamp": zod.string().optional().describe('밀리세컨드 단위 타임스탬프. nonce 대신 사용할 수 있습니다.'),
  "nonce": zod.string().optional().describe('timestamp 대신 사용할 수 있는 증가하는 난스 값.'),
  "signature": zod.string().describe('HMAC-SHA512 서명값(base64 인코딩).'),
  "receive-window": zod.number().min(getbalancesHeaderReceiveWindowMin).max(getbalancesHeaderReceiveWindowMax).optional().describe('리시브 윈도 (200~60000 밀리세컨드).')
})


/**
 * @summary 특정 자산 잔고 조회
 */
export const GetbalancesassetnameParams = zod.object({
  "AssetName": zod.string().describe('자산 이름 (예: BTC)')
})

export const getbalancesassetnameHeaderReceiveWindowMin = 200;
export const getbalancesassetnameHeaderReceiveWindowMax = 60000;



export const GetbalancesassetnameHeader = zod.object({
  "timestamp": zod.string().optional().describe('밀리세컨드 단위 타임스탬프. nonce 대신 사용할 수 있습니다.'),
  "nonce": zod.string().optional().describe('timestamp 대신 사용할 수 있는 증가하는 난스 값.'),
  "signature": zod.string().describe('HMAC-SHA512 서명값(base64 인코딩).'),
  "receive-window": zod.number().min(getbalancesassetnameHeaderReceiveWindowMin).max(getbalancesassetnameHeaderReceiveWindowMax).optional().describe('리시브 윈도 (200~60000 밀리세컨드).')
})


/**
 * GET /orders에 한하여 쿼리스트링이 시그니쳐 생성 과정에 포함되어야 합니다. 문서 상단의 예시 코드를 참고하세요.
 * @summary 주문 조회
 */
export const GetordersQueryParams = zod.object({
  "includePast": zod.boolean().optional().describe('true일 경우 완전 체결 혹은 취소된 주문들도 조회 결과에 포함됨(완전 체결 혹은 취소 시점부터 10분 동안만 조회가 가능)'),
  "pagination": zod.boolean().optional().describe('리턴되는 주문 수가 3천 개를 초과할 경우에는true로 설정하여 페이지 별로 1천 개씩 접근 필요'),
  "tradingPairName": zod.string().optional().describe('해당 거래쌍 주문 조회 (BTC-KRW, ETH-KRW ...)'),
  "status": zod.string().optional().describe('주문 상태별로 조회(placed, cancelled, completed, updated, reserved)'),
  "since": zod.number().optional().describe('시작 시점 타임 스탬프 (밀리세컨드 단위)'),
  "filterByUpdatedAt": zod.boolean().optional().describe('since와 함께 사용true: 시작 시점이 updatedAt 기준false: 시작 시점이 createdAt 기준'),
  "limit": zod.number().optional().describe('최대 주문 개수'),
  "tail": zod.boolean().optional().describe('limit과 함께 사용 true: 최근 주문부터 limit 만큼 데이터 조회false: 오래된 주문부터 limit 만큼 데이터 조회')
})

export const getordersHeaderReceiveWindowMin = 200;
export const getordersHeaderReceiveWindowMax = 60000;



export const GetordersHeader = zod.object({
  "timestamp": zod.string().optional().describe('밀리세컨드 단위 타임스탬프. nonce 대신 사용할 수 있습니다.'),
  "nonce": zod.string().optional().describe('timestamp 대신 사용할 수 있는 증가하는 난스 값.'),
  "signature": zod.string().describe('HMAC-SHA512 서명값(base64 인코딩).'),
  "receive-window": zod.number().min(getordersHeaderReceiveWindowMin).max(getordersHeaderReceiveWindowMax).optional().describe('리시브 윈도 (200~60000 밀리세컨드).')
})


/**
 * 지정가 주문 시 amount는 무조건 base 자산을 단위로 합니다. 시장가 주문 시 amount는 매도의 경우에는 base 자산을 단위로, 매수의 경우는 quote 자산을 단위로 합니다. 예를 들어, ETH-KRW 오더북에서 지정가는 매도 매수 관계없이 단위가 ETH인 반면, 시장가 매도는 단위가 ETH이고 시장가 매수는 단위가 KRW이 됩니다.

모든 거래 수수료는 거래쌍의 quote 자산으로 지불됩니다. (2022년 11월 1일 정기점검 이후 적용) 매도 주문의 경우 매도 완료 후 얻게된 quote 자산에 대하여 수수료율을 적용합니다. 예를 들어, 매도 거래에서 10,000원을 받은 사용자가 거래 수수료로 20원(수수료율 0.2% 가정)을 지불한 후 사용자는 9980원을 받게 됩니다. 매수 주문의 경우 매수자는 주문을 한 quote amount 외에 수수료를 지불할 수 있는 충분한 잔고가 필요합니다. (quote balance > order quote amount + fee (amount * fee rate)) 예를 들어, 사용자가 10,000원 매수 주문 시, 최소 10,020원 필요합니다. (수수료율 0.2% 가정)

REST API를 통한 최소 주문 금액은 quote 자산이 KRW일 경우 1,000 KRW이고, quote 자산이 USDC일 경우 1 USDC입니다.

클라이언트 오더 ID는 사용자가 주문에 대해 부여할 수 있는 커스텀 ID입니다. 주문을 등록/조회/취소할 때 클라이언트 오더 ID를 사용할 수 있습니다.

예약주문은 감시가격을 지정하여 주문을 예약해 놓았다가, 현재가가 감시가격에 도달했을 시에 주문을 등록하는 기능으로 스탑오더라고도 불립니다. 참고로 예약지정가 주문만 지원하며 예약시장가 주문은 시장 안정성을 위해 허용되지 않습니다.

프로텍션은 주문 시 해당 주문의 최초 체결가를 기준, 10%를 초과한 가격에 매도/매수 주문이 체결되는 것을 막는 주문 보호 기능입니다. 가격이 10%를 초과하게 되면 해당 주문은 중도 취소되고 잔량은 고객에게 되돌려집니다. 지정가 및 시장가 주문 모두 적용 가능합니다.

지정가 주문 유형에서 po(post only)는 즉시 체결되는 상대 주문이 있으면 주문을 취소하고 그렇지 않으면 주문을 전량 등록하는 조건(전량 오더북에 올림 or 전량 취소)입니다. ioc(immediate-or-cancel)는 즉시 체결할 수 있는 만큼 최대한 체결한 후에 잔량은 오더북에 올리지 않고 중도 취소하는 조건(즉시 체결 then 잔량 취소)입니다. fok(fill-or-kill)는 수량 전부를 즉시 체결할 수 있는 경우에만 주문을 넣고 그렇지 않은 경우에는 전량 취소하는 조건(전량 즉시 체결 or 전량 취소)입니다. 참고로, 시장가 주문일 경우 지정가 주문 유형은 무시되며, 프로텍션을 yes로 설정한 경우에는 ioc와 fok를 사용할 수 없습니다.
 * @summary 주문 등록
 */
export const postordersHeaderReceiveWindowMin = 200;
export const postordersHeaderReceiveWindowMax = 60000;



export const PostordersHeader = zod.object({
  "timestamp": zod.string().optional().describe('밀리세컨드 단위 타임스탬프. nonce 대신 사용할 수 있습니다.'),
  "nonce": zod.string().optional().describe('timestamp 대신 사용할 수 있는 증가하는 난스 값.'),
  "signature": zod.string().describe('HMAC-SHA512 서명값(base64 인코딩).'),
  "receive-window": zod.number().min(postordersHeaderReceiveWindowMin).max(postordersHeaderReceiveWindowMax).optional().describe('리시브 윈도 (200~60000 밀리세컨드).')
})

export const PostordersBody = zod.object({
  "clientOrderId": zod.string().optional().describe('클라이언트 오더 ID로 최대 20자이고 [a-zA-Z0-9_-] 문자 사용 가능'),
  "tradingPairName": zod.string().describe('오더북'),
  "side": zod.string().describe('buy(구매), sell(판매)'),
  "type": zod.string().describe('limit(지정가), market(시장가)'),
  "price": zod.number().describe('주문 가격'),
  "stopPrice": zod.number().optional().describe('감시 가격'),
  "amount": zod.number().describe('주문 수량'),
  "protection": zod.string().optional().describe('최초 체결가 기준 ±10% 초과되는 주문 취소 여부로 yes\/no 중 택일'),
  "timeInForce": zod.string().optional().describe('지정가 주문 유형으로 gtc\/po\/ioc\/fok 중 택일')
})


/**
 * 완전 체결 혹은 취소된 주문은 완전 체결 혹은 취소 시점부터 10분 동안만 조회가 가능합니다.
 * @summary 특정 주문 조회
 */
export const GetordersorderidParams = zod.object({
  "OrderId": zod.string().describe('주문 ID')
})

export const getordersorderidHeaderReceiveWindowMin = 200;
export const getordersorderidHeaderReceiveWindowMax = 60000;



export const GetordersorderidHeader = zod.object({
  "timestamp": zod.string().optional().describe('밀리세컨드 단위 타임스탬프. nonce 대신 사용할 수 있습니다.'),
  "nonce": zod.string().optional().describe('timestamp 대신 사용할 수 있는 증가하는 난스 값.'),
  "signature": zod.string().describe('HMAC-SHA512 서명값(base64 인코딩).'),
  "receive-window": zod.number().min(getordersorderidHeaderReceiveWindowMin).max(getordersorderidHeaderReceiveWindowMax).optional().describe('리시브 윈도 (200~60000 밀리세컨드).')
})


/**
 * 해당하는 오더가 존재하지 않으면 404 에러가 반환됩니다.
 * @summary 주문 취소
 */
export const DeleteordersorderidParams = zod.object({
  "OrderId": zod.string().describe('주문 ID')
})

export const deleteordersorderidHeaderReceiveWindowMin = 200;
export const deleteordersorderidHeaderReceiveWindowMax = 60000;



export const DeleteordersorderidHeader = zod.object({
  "timestamp": zod.string().optional().describe('밀리세컨드 단위 타임스탬프. nonce 대신 사용할 수 있습니다.'),
  "nonce": zod.string().optional().describe('timestamp 대신 사용할 수 있는 증가하는 난스 값.'),
  "signature": zod.string().describe('HMAC-SHA512 서명값(base64 인코딩).'),
  "receive-window": zod.number().min(deleteordersorderidHeaderReceiveWindowMin).max(deleteordersorderidHeaderReceiveWindowMax).optional().describe('리시브 윈도 (200~60000 밀리세컨드).')
})


/**
 * 해당 개인 API로는 본인 주문 관련 체결 내역만 조회됩니다. 본인 주문 가릴 것 없이 모든 체결 기록 조회를 위해서는 공개 API의 체결 기록 조회 기능을 사용하세요.
 * @summary 체결 기록 조회
 */
export const GettradesQueryParams = zod.object({
  "limit": zod.number().optional().describe('반환되는 항목의 개수 (최대 100)'),
  "pastmax": zod.number().optional().describe('이 ID보다 오래된 데이터를 조회'),
  "latestmin": zod.number().optional().describe('이 ID보다 새로운 최신 데이터를 조회'),
  "after": zod.number().optional().describe('이 타임스탬프 이후의 데이터를 조회 (초 단위)'),
  "before": zod.number().optional().describe('이 타임스탬프 이전의 데이터를 조회 (초 단위)'),
  "deepSearch": zod.boolean().optional().describe('true인 경우에 한하여 한 달 이상 지난 데이터까지 모두 포함하여 조회(다른 파라미터들보다 더 높은 우선순위를 가짐)'),
  "tradingPairName": zod.string().optional().describe('해당 거래쌍의 데이터 조회 (BTC-KRW, ETH-KRW...)')
})

export const gettradesHeaderReceiveWindowMin = 200;
export const gettradesHeaderReceiveWindowMax = 60000;



export const GettradesHeader = zod.object({
  "timestamp": zod.string().optional().describe('밀리세컨드 단위 타임스탬프. nonce 대신 사용할 수 있습니다.'),
  "nonce": zod.string().optional().describe('timestamp 대신 사용할 수 있는 증가하는 난스 값.'),
  "signature": zod.string().describe('HMAC-SHA512 서명값(base64 인코딩).'),
  "receive-window": zod.number().min(gettradesHeaderReceiveWindowMin).max(gettradesHeaderReceiveWindowMax).optional().describe('리시브 윈도 (200~60000 밀리세컨드).')
})


/**
 * @summary 입출금 기록 조회
 */
export const GetdepositwithdrawalstatusQueryParams = zod.object({
  "limit": zod.number().optional().describe('반환되는 항목의 개수 (최대 20)'),
  "latestmin": zod.number().optional().describe('이 ID보다 오래된 데이터를 조회'),
  "after": zod.number().optional().describe('이 타임스탬프 이후의 데이터를 조회 (ms 단위)'),
  "before": zod.number().optional().describe('이 타임스탬프 이전의 데이터를 조회 (ms 단위)'),
  "completedOnly": zod.boolean().optional().describe('완료된 입출금 내역만 조회 (true\/false 중 택일)'),
  "asset": zod.string().optional().describe('해당 자산의 입출금 내역 조회 (BTC, ETH ...)')
})

export const getdepositwithdrawalstatusHeaderReceiveWindowMin = 200;
export const getdepositwithdrawalstatusHeaderReceiveWindowMax = 60000;



export const GetdepositwithdrawalstatusHeader = zod.object({
  "timestamp": zod.string().optional().describe('밀리세컨드 단위 타임스탬프. nonce 대신 사용할 수 있습니다.'),
  "nonce": zod.string().optional().describe('timestamp 대신 사용할 수 있는 증가하는 난스 값.'),
  "signature": zod.string().describe('HMAC-SHA512 서명값(base64 인코딩).'),
  "receive-window": zod.number().min(getdepositwithdrawalstatusHeaderReceiveWindowMin).max(getdepositwithdrawalstatusHeaderReceiveWindowMax).optional().describe('리시브 윈도 (200~60000 밀리세컨드).')
})


/**
 * @summary 가상자산 입금 주소 조회
 */
export const getcryptodepositaddressesHeaderReceiveWindowMin = 200;
export const getcryptodepositaddressesHeaderReceiveWindowMax = 60000;



export const GetcryptodepositaddressesHeader = zod.object({
  "timestamp": zod.string().optional().describe('밀리세컨드 단위 타임스탬프. nonce 대신 사용할 수 있습니다.'),
  "nonce": zod.string().optional().describe('timestamp 대신 사용할 수 있는 증가하는 난스 값.'),
  "signature": zod.string().describe('HMAC-SHA512 서명값(base64 인코딩).'),
  "receive-window": zod.number().min(getcryptodepositaddressesHeaderReceiveWindowMin).max(getcryptodepositaddressesHeaderReceiveWindowMax).optional().describe('리시브 윈도 (200~60000 밀리세컨드).')
})


/**
 * @summary 가상자산 출금 주소 조회
 */
export const getcryptowithdrawaladdressesHeaderReceiveWindowMin = 200;
export const getcryptowithdrawaladdressesHeaderReceiveWindowMax = 60000;



export const GetcryptowithdrawaladdressesHeader = zod.object({
  "timestamp": zod.string().optional().describe('밀리세컨드 단위 타임스탬프. nonce 대신 사용할 수 있습니다.'),
  "nonce": zod.string().optional().describe('timestamp 대신 사용할 수 있는 증가하는 난스 값.'),
  "signature": zod.string().describe('HMAC-SHA512 서명값(base64 인코딩).'),
  "receive-window": zod.number().min(getcryptowithdrawaladdressesHeaderReceiveWindowMin).max(getcryptowithdrawaladdressesHeaderReceiveWindowMax).optional().describe('리시브 윈도 (200~60000 밀리세컨드).')
})


/**
 * 사전에 등록된 IP에서만 출금이 가능합니다.
 * @summary 가상자산 출금
 */
export const postwithdrawalsHeaderReceiveWindowMin = 200;
export const postwithdrawalsHeaderReceiveWindowMax = 60000;



export const PostwithdrawalsHeader = zod.object({
  "timestamp": zod.string().optional().describe('밀리세컨드 단위 타임스탬프. nonce 대신 사용할 수 있습니다.'),
  "nonce": zod.string().optional().describe('timestamp 대신 사용할 수 있는 증가하는 난스 값.'),
  "signature": zod.string().describe('HMAC-SHA512 서명값(base64 인코딩).'),
  "receive-window": zod.number().min(postwithdrawalsHeaderReceiveWindowMin).max(postwithdrawalsHeaderReceiveWindowMax).optional().describe('리시브 윈도 (200~60000 밀리세컨드).')
})

export const PostwithdrawalsBody = zod.object({
  "asset": zod.string().describe('자산 이름'),
  "nickname": zod.string().describe('출금 주소 별칭'),
  "amount": zod.string().describe('출금 수량')
})


/**
 * 완전 체결 혹은 취소된 주문은 완전 체결 혹은 취소 시점부터 10분 동안만 조회가 가능합니다.
 * @summary 클라이언트 주문 ID로 특정 주문 조회
 */
export const GetordersclientorderidParams = zod.object({
  "ClientOrderID": zod.string().describe('클라이언트 오더 ID')
})

export const getordersclientorderidHeaderReceiveWindowMin = 200;
export const getordersclientorderidHeaderReceiveWindowMax = 60000;



export const GetordersclientorderidHeader = zod.object({
  "timestamp": zod.string().optional().describe('밀리세컨드 단위 타임스탬프. nonce 대신 사용할 수 있습니다.'),
  "nonce": zod.string().optional().describe('timestamp 대신 사용할 수 있는 증가하는 난스 값.'),
  "signature": zod.string().describe('HMAC-SHA512 서명값(base64 인코딩).'),
  "receive-window": zod.number().min(getordersclientorderidHeaderReceiveWindowMin).max(getordersclientorderidHeaderReceiveWindowMax).optional().describe('리시브 윈도 (200~60000 밀리세컨드).')
})


/**
 * 해당하는 오더가 존재하지 않으면 404 에러가 반환됩니다.
 * @summary 클라이언트 주문 ID로 주문 취소
 */
export const DeleteordersclientorderidParams = zod.object({
  "ClientOrderID": zod.string().describe('클라이언트 오더 ID')
})

export const deleteordersclientorderidHeaderReceiveWindowMin = 200;
export const deleteordersclientorderidHeaderReceiveWindowMax = 60000;



export const DeleteordersclientorderidHeader = zod.object({
  "timestamp": zod.string().optional().describe('밀리세컨드 단위 타임스탬프. nonce 대신 사용할 수 있습니다.'),
  "nonce": zod.string().optional().describe('timestamp 대신 사용할 수 있는 증가하는 난스 값.'),
  "signature": zod.string().describe('HMAC-SHA512 서명값(base64 인코딩).'),
  "receive-window": zod.number().min(deleteordersclientorderidHeaderReceiveWindowMin).max(deleteordersclientorderidHeaderReceiveWindowMax).optional().describe('리시브 윈도 (200~60000 밀리세컨드).')
})
