/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Upbit Quotation API
 * 업비트 시세 조회 API. 공식 개발자 센터 v1.6.1 기준 스키마입니다.
 * OpenAPI spec version: 1.6.1
 */
import * as zod from 'zod';

/**
 * @summary 페어 목록 조회
 */
export const ListTradingPairsQueryParams = zod.object({
  "is_details": zod.boolean().optional()
})


/**
 * @summary 초(Second) 캔들 조회
 */
export const getSecondCandlesQueryCountDefault = 1;

export const GetSecondCandlesQueryParams = zod.object({
  "market": zod.string(),
  "to": zod.string().optional(),
  "count": zod.number().default(getSecondCandlesQueryCountDefault)
})


/**
 * @summary 분(Minute) 캔들 조회
 */
export const GetMinuteCandlesParams = zod.object({
  "unit": zod.union([zod.literal(1),zod.literal(3),zod.literal(5),zod.literal(10),zod.literal(15),zod.literal(30),zod.literal(60),zod.literal(240)])
})

export const getMinuteCandlesQueryCountDefault = 1;

export const GetMinuteCandlesQueryParams = zod.object({
  "market": zod.string(),
  "to": zod.string().optional(),
  "count": zod.number().default(getMinuteCandlesQueryCountDefault)
})


/**
 * @summary 일(Day) 캔들 조회
 */
export const getDayCandlesQueryCountDefault = 1;

export const GetDayCandlesQueryParams = zod.object({
  "market": zod.string(),
  "to": zod.string().optional(),
  "count": zod.number().default(getDayCandlesQueryCountDefault),
  "converting_price_unit": zod.string().optional()
})


/**
 * @summary 주(Week) 캔들 조회
 */
export const getWeekCandlesQueryCountDefault = 1;

export const GetWeekCandlesQueryParams = zod.object({
  "market": zod.string(),
  "to": zod.string().optional(),
  "count": zod.number().default(getWeekCandlesQueryCountDefault)
})


/**
 * @summary 월(Month) 캔들 조회
 */
export const getMonthCandlesQueryCountDefault = 1;

export const GetMonthCandlesQueryParams = zod.object({
  "market": zod.string(),
  "to": zod.string().optional(),
  "count": zod.number().default(getMonthCandlesQueryCountDefault)
})


/**
 * @summary 연(Year) 캔들 조회
 */
export const getYearCandlesQueryCountDefault = 1;

export const GetYearCandlesQueryParams = zod.object({
  "market": zod.string(),
  "to": zod.string().optional(),
  "count": zod.number().default(getYearCandlesQueryCountDefault)
})


/**
 * @summary 최근 체결 내역 조회
 */
export const listTradesTicksQueryCountDefault = 1;

export const ListTradesTicksQueryParams = zod.object({
  "market": zod.string(),
  "to": zod.string().optional(),
  "count": zod.number().default(listTradesTicksQueryCountDefault),
  "cursor": zod.string().optional(),
  "days_ago": zod.number().optional()
})


/**
 * @summary 페어 단위 현재가 조회
 */
export const ListTickersQueryParams = zod.object({
  "markets": zod.string()
})


/**
 * @summary 마켓 단위 현재가 조회
 */
export const ListQuoteTickersQueryParams = zod.object({
  "quote_currencies": zod.string()
})


/**
 * @summary 호가 조회
 */
export const listOrderbooksQueryLevelDefault = `0`;
export const listOrderbooksQueryCountDefault = 30;

export const ListOrderbooksQueryParams = zod.object({
  "markets": zod.string(),
  "level": zod.enum(['0', '10000', '100000', '1000000', '10000000', '100000000']).default(listOrderbooksQueryLevelDefault),
  "count": zod.number().default(listOrderbooksQueryCountDefault)
})


/**
 * @summary 호가 정책 조회
 */
export const ListOrderbookInstrumentsQueryParams = zod.object({
  "markets": zod.string()
})


/**
 * @deprecated
 * @summary 호가 모아보기 단위 조회
 */
export const ListOrderbookSupportedLevelsQueryParams = zod.object({
  "markets": zod.string()
})
